# Oranges theme configuration

favicon:
  enable: true
  icon: /images/favicon.png
  touch_icon: /images/favicon.png

avatar:
  author_photo: /images/favicon.png
  author_nickname: Frank
  path: /

navbar:
  -
    name: 首页
    enable: true
    path: /
    key: home
  -
    name: 归档
    enable: true
    path: /archives/
    key: archives
  -
    name: 分类
    enable: false
    path: /categories/
    key: categories
  -
    name: 标签
    enable: true
    path: /tags/
    key: tags
  -
    name: 关于
    enable: true
    path: /about/
    key: about

catalog:
  enable: true

prevnext:
  enable: true

footer:
  social:
    -
      name: github
      icon: github
      path: https://github.com/RainbowJier
  more:
    -
      name: Copyright © {thisYear} Frank
      path: https://github.com/RainbowJier
    -
      name: 主题 Oranges | 由 Hexo 驱动
      path: https://github.com/zchengsite/hexo-theme-oranges
search:
  enable: true
  placeholder:

colorSwitch:
  enable: true

postShare:
  enable: true
  twitter:
    enable: true
  facebook:
    enable: true

codeBlock:
  style: normal
  copy:
    enable: true

themeColor: '#808080'
